name: Create EFI

on:
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Download IASL
        run: |
          sudo apt update
          sudo apt -y install acpica-tools

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Compile SSDTs
        run: |
          cd ACPI
          for acpiSrc in *.dsl
          do {
            iasl ${acpiSrc}
          }
          done

      - name: Prepare artifact
        run: |
          mkdir -p out/EFI/OC
          cp -r ACPI Drivers Kexts Resources Tools config.plist OpenCore.efi out/EFI/OC
          cd out/EFI/OC
          rm -rf ACPI/*.dsl README.md .git .github

      - name: Upload as artifact
        uses: actions/upload-artifact@v4
        with:
          name: "EFI"
          path: out
